apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-kezy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-kezy
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-kezy
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-kezy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-kezy
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-iayn-tenant/rhtap-demo-app/hacbs-test-project-kezy@sha256:fc94c1ed8a7d9d804e7affe86741434bd3945ce6ebed4f150b9bc7f241b0b947
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
